### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'graspologic' when running lightrag_ollama_demo.py

### ISSUE THREAD

**Issue by BireleyX** [HKUDS/LightRAG#958]
### Do you need to file an issue?

- [x] I have searched the existing issues and this bug is not already filed.
- [ ] I believe this is a legitimate bug, not just a question or feature request.

### Describe the bug

When executing lightrag_ollama_demo.py, I get the following error:

Traceback (most recent call last):
  File "C:\Dev\LightRAG\examples\lightrag_ollama_demo.py", line 16, in <module>
    rag = LightRAG(
        working_dir=WORKING_DIR,
    ...<11 lines>...
        ),
    )
  File "<string>", line 37, in __init__
  File "C:\Dev\LightRAG\lightrag\lightrag.py", line 350, in __post_init__
    self.chunk_entity_relation_graph: BaseGraphStorage = self.graph_storage_cls(  # type: ignore
                                                         ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
        namespace=make_namespace(
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        embedding_func=self.embedding_func,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Dev\LightRAG\lightrag\utils.py", line 780, in import_class
    module = importlib.import_module(module_name, package=package)
  File "C:\Users\birel\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Dev\LightRAG\lightrag\kg\networkx_impl.py", line 25, in <module>
    from graspologic import embed
ModuleNotFoundError: No module named 'graspologic'

==========================================

When attempting to install graspologic, I get:

  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [78 lines of output]
      C:\Users\birel\AppData\Local\Temp\pip-build-env-2mqs1z9c\overlay\Lib\site-packages\setuptools\_distutils\dist.py:270: UserWarning: Unknown distribution option: 'test_suite'
        warnings.warn(msg)
      C:\Users\birel\AppData\Local\Temp\pip-build-env-2mqs1z9c\overlay\Lib\site-packages\setuptools\_distutils\dist.py:270: UserWarning: Unknown distribution option: 'tests_require'
        warnings.warn(msg)
      running dist_info
      creating C:\Users\birel\AppData\Local\Temp\pip-modern-metadata-a4ctva3t\gensim.egg-info
      writing C:\Users\birel\AppData\Local\Temp\pip-modern-metadata-a4ctva3t\gensim.egg-info\PKG-INFO
      writing dependency_links to C:\Users\birel\AppData\Local\Temp\pip-modern-metadata-a4ctva3t\gensim.egg-info\dependency_links.txt  
      writing requirements to C:\Users\birel\AppData\Local\Temp\pip-modern-metadata-a4ctva3t\gensim.egg-info\requires.txt
      writing top-level names to C:\Users\birel\AppData\Local\Temp\pip-modern-metadata-a4ctva3t\gensim.egg-info\top_level.txt
      writing manifest file 'C:\Users\birel\AppData\Local\Temp\pip-modern-metadata-a4ctva3t\gensim.egg-info\SOURCES.txt'
      Traceback (most recent call last):
        File "c:\Dev\LightRAG\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 389, in <module>   
          main()
          ~~~~^^
        File "c:\Dev\LightRAG\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 373, in main       
          json_out["return_val"] = hook(**hook_input["kwargs"])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "c:\Dev\LightRAG\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 175, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "C:\Users\birel\AppData\Local\Temp\pip-build-env-2mqs1z9c\overlay\Lib\site-packages\setuptools\build_meta.py", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\birel\AppData\Local\Temp\pip-build-env-2mqs1z9c\overlay\Lib\site-packages\setuptools\build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\birel\AppData\Local\Temp\pip-build-env-2mqs1z9c\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 367, in <module>
        File "C:\Users\birel\AppData\Local\Temp\pip-build-env-2mqs1z9c\overlay\Lib\site-packages\setuptools\__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "C:\Users\birel\AppData\Local\Temp\pip-build-env-2mqs1z9c\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 186, in setup
          return run_commands(dist)
        File "C:\Users\birel\AppData\Local\Temp\pip-build-env-2mqs1z9c\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 202, in run_commands
          dist.run_commands()
          ~~~~~~~~~~~~~~~~~^^
        File "C:\Users\birel\AppData\Local\Temp\pip-build-env-2mqs1z9c\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 983, in run_commands
          self.run_command(cmd)
          ~~~~~~~~~~~~~~~~^^^^^
        File "C:\Users\birel\AppData\Local\Temp\pip-build-env-2mqs1z9c\overlay\Lib\site-packages\setuptools\dist.py", line 999, in run_command
          super().run_command(command)
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "C:\Users\birel\AppData\Local\Temp\pip-build-env-2mqs1z9c\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 1002, in run_command
          cmd_obj.run()
          ~~~~~~~~~~~^^
        File "C:\Users\birel\AppData\Local\Temp\pip-build-env-2mqs1z9c\overlay\Lib\site-packages\setuptools\command\dist_info.py", line 94, in run
          self.egg_info.run()
          ~~~~~~~~~~~~~~~~~^^
        File "C:\Users\birel\AppData\Local\Temp\pip-build-env-2mqs1z9c\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 312, in run
          self.find_sources()
          ~~~~~~~~~~~~~~~~~^^
        File "C:\Users\birel\AppData\Local\Temp\pip-build-env-2mqs1z9c\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 320, in find_sources
          mm.run()
          ~~~~~~^^
        File "C:\Users\birel\AppData\Local\Temp\pip-build-env-2mqs1z9c\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 543, in run
          self.add_defaults()
          ~~~~~~~~~~~~~~~~~^^
        File "C:\Users\birel\AppData\Local\Temp\pip-build-env-2mqs1z9c\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 581, in add_defaults
          sdist.add_defaults(self)
          ~~~~~~~~~~~~~~~~~~^^^^^^
        File "C:\Users\birel\AppData\Local\Temp\pip-build-env-2mqs1z9c\overlay\Lib\site-packages\setuptools\command\sdist.py", line 109, in add_defaults
          super().add_defaults()
          ~~~~~~~~~~~~~~~~~~~~^^
        File "C:\Users\birel\AppData\Local\Temp\pip-build-env-2mqs1z9c\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 239, in add_defaults
          self._add_defaults_ext()
          ~~~~~~~~~~~~~~~~~~~~~~^^
        File "C:\Users\birel\AppData\Local\Temp\pip-build-env-2mqs1z9c\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 323, in _add_defaults_ext
          build_ext = self.get_finalized_command('build_ext')
        File "C:\Users\birel\AppData\Local\Temp\pip-build-env-2mqs1z9c\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in get_finalized_command
          cmd_obj.ensure_finalized()
          ~~~~~~~~~~~~~~~~~~~~~~~~^^
        File "C:\Users\birel\AppData\Local\Temp\pip-build-env-2mqs1z9c\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 124, in ensure_finalized
          self.finalize_options()
          ~~~~~~~~~~~~~~~~~~~~~^^
        File "<string>", line 111, in finalize_options
      AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__' and no __dict__ for setting new attributes
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed


### Steps to reproduce

Followed all setup instructions for lightrag and ollama.
After correctly modifying examples/lightrag_ollama_demo.py with choice of ollama models, execute the script.

### Expected Behavior

No errors.

### LightRAG Config Used

v1.2.2
Ollama = llama3.1:latest, nomic-embed-text
[lightrag_ollama_demo.py](https://github.com/HKUDS/LightRAG/blob/main/examples/lightrag_ollama_demo.py)


### Logs and screenshots

_No response_

### Additional Information

- LightRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by tonyatpeking** [comment]
Same issue here. Downgrading python 3.13 -> 3.12 fixed it for me. From the graspologic they list python 3.12 as their latest supported version.

**Comment by Mybigwang** [comment]
i have similar issue about gensim,  it shows cant find some h file in word2vec.c file of gensim when i use python 3.13. Then, i use python 3.10 retrying and it fixed.

**Comment by BireleyX** [comment]
Issue is fixed. latest codebase 1.2.6 works with python 3.12.5
