### ISSUE TITLE
Using MongoDB as KVStorage results in AttributeError: 'dict' object has no attribute 'status'

### ISSUE THREAD

**Issue by ArnoChenFx** [HKUDS/LightRAG#706]
When using MongoDB as the KVStorage, I encountered the following error during execution:

```python
AttributeError: 'dict' object has no attribute 'status'
```

After investigation, it appears that this issue was introduced by the changes in PR #695 .

**Steps to Reproduce:**  
1. Configure and use MongoDB as the KVStorage.  
2. Perform an operation that accesses the document status.  
3. Observe the error being raised.

**Expected Behavior:**  
- The code should access the status field using the key-based access method (i.e., `current_doc["status"]`) for dictionary objects, or alternatively, return an object that supports attribute-style access.

**Suggested Fix:**  
- Review the changes introduced in PR #695.  
- Adjust the code to either use the correct key access method for dictionaries or modify the returned object to support attribute access.

Please review and address this issue. Thank you!
