### ISSUE TITLE
ERROR:lightrag:Error while deleting document : 'JsonKVStorage' object has no attribute 'get'

### ISSUE THREAD

**Issue by fatehss** [HKUDS/LightRAG#757]
Currently, the following code does not work: `rag.delete_by_doc_id(doc_id="doc-e8d7db6e5bcf7ec440ee8831e5842882")` when using JsonKVStorage class.

Terminal output: 
```
LightRAG$ python lightrag_test.py 
INFO:nano-vectordb:Load (26, 3072) data
INFO:nano-vectordb:Init {'embedding_dim': 3072, 'metric': 'cosine', 'storage_file': './sample_dir_2/vdb_entities.json'} 26 data
INFO:nano-vectordb:Load (25, 3072) data
INFO:nano-vectordb:Init {'embedding_dim': 3072, 'metric': 'cosine', 'storage_file': './sample_dir_2/vdb_relationships.json'} 25 data
INFO:nano-vectordb:Load (3, 3072) data
INFO:nano-vectordb:Init {'embedding_dim': 3072, 'metric': 'cosine', 'storage_file': './sample_dir_2/vdb_chunks.json'} 3 data
INFO:lightrag:Loaded document status storage with 2 records
ERROR:lightrag:Error while deleting document doc-e8d7db6e5bcf7ec440ee8831e5842882: 'JsonDocStatusStorage' object has no attribute 'get'
```

Bisected issue to this commit: `fe3050adcea36c67bac854f20faa762d6b187e8b` which gives error of `ERROR:lightrag:Error while deleting document doc-e8d7db6e5bcf7ec440ee8831e5842882: 'JsonDocStatusStorage' object has no attribute 'filter'`

**Comment by YanSte** [comment]
Pull request is coming
