### ISSUE TITLE
[Bug]:Neo4JStorage crash in v1.4.9.9 – 'Neo4JStorage' object has no attribute 'workspace' (works in v1.4.9.8)

### ISSUE THREAD

**Issue by akash171198** [HKUDS/LightRAG#2525]
### Do you need to file an issue?

- [ ] I have searched the existing issues and this bug is not already filed.
- [ ] I believe this is a legitimate bug, not just a question or feature request.

### Describe the bug

After upgrading LightRAG from v1.4.9.8 to v1.4.9.9, the application fails to start when using Neo4JStorage as the graph backend.

The same configuration works correctly in v1.4.9.8, but in v1.4.9.9 LightRAG crashes during initialization with the following error:

AttributeError: 'Neo4JStorage' object has no attribute 'workspace'

This happens before any Neo4j connection is established.

### Steps to reproduce

- Run LightRAG using Docker image:

ghcr.io/hkuds/lightrag:v1.4.9.9

- Configure Neo4j as the graph storage backend:
LIGHTRAG_GRAPH_STORAGE=Neo4JStorage

- Use the following Neo4j environment variables:

NEO4J_URI=bolt://192.168.31.228:7687
NEO4J_USERNAME=neo4j
NEO4J_PASSWORD=********
NEO4J_DATABASE=neo4j
NEO4J_MAX_CONNECTION_POOL_SIZE=100
NEO4J_CONNECTION_TIMEOUT=30
NEO4J_CONNECTION_ACQUISITION_TIMEOUT=30
NEO4J_MAX_TRANSACTION_RETRY_TIME=30
NEO4J_MAX_CONNECTION_LIFETIME=300
NEO4J_LIVENESS_CHECK_TIMEOUT=30
NEO4J_KEEP_ALIVE=true
NEO4J_WORKSPACE=business

- Start the LightRAG server.

### Expected Behavior

LightRAG should start successfully, initialize Neo4JStorage, and connect to Neo4j — same as behavior in v1.4.9.8.

### LightRAG Config Used

LIGHTRAG_GRAPH_STORAGE=Neo4JStorage

NEO4J_URI=bolt://192.168.31.228:7687
NEO4J_USERNAME=neo4j
NEO4J_PASSWORD=********
NEO4J_DATABASE=neo4j
NEO4J_MAX_CONNECTION_POOL_SIZE=100
NEO4J_CONNECTION_TIMEOUT=30
NEO4J_CONNECTION_ACQUISITION_TIMEOUT=30
NEO4J_MAX_TRANSACTION_RETRY_TIME=30
NEO4J_MAX_CONNECTION_LIFETIME=300
NEO4J_LIVENESS_CHECK_TIMEOUT=30
NEO4J_KEEP_ALIVE=true
NEO4J_WORKSPACE=business

### Logs and screenshots

⚠️  Security Notice:
lightrag-third  |     JWT authentication is enabled.
lightrag-third  |     Make sure to login before making the request, and include the 'Authorization' in the header.
lightrag-third  |
lightrag-third  | INFO: Embedding config: binding=openai model=nomic-embed-text:latest embedding_dim=768 max_token_size=8192
lightrag-third  | INFO: Send embedding dimension: False by env var (dimensions=768, has_param=True, binding=openai)
lightrag-third  | INFO: Embedding max_token_size: 8192 (from openai provider default)
lightrag-third  | INFO: Reranking is disabled
lightrag-third  | ERROR: Failed to initialize LightRAG: 'Neo4JStorage' object has no attribute 'workspace'
lightrag-third  | Traceback (most recent call last):
lightrag-third  |   File "<frozen runpy>", line 198, in _run_module_as_main
lightrag-third  |   File "<frozen runpy>", line 88, in _run_code
lightrag-third  |   File "/app/lightrag/api/lightrag_server.py", line 1527, in <module>
lightrag-third  |     main()
lightrag-third  |   File "/app/lightrag/api/lightrag_server.py", line 1502, in main
lightrag-third  |     app = create_app(global_args)
lightrag-third  |           ^^^^^^^^^^^^^^^^^^^^^^^
lightrag-third  |   File "/app/lightrag/api/lightrag_server.py", line 1049, in create_app
lightrag-third  |     rag = LightRAG(
lightrag-third  |           ^^^^^^^^^
lightrag-third  |   File "<string>", line 56, in __init__
lightrag-third  |   File "/app/lightrag/lightrag.py", line 619, in __post_init__
lightrag-third  |     self.chunk_entity_relation_graph: BaseGraphStorage = self.graph_storage_cls(  # type: ignore
lightrag-third  |                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lightrag-third  |   File "/app/lightrag/utils.py", line 1881, in import_class
lightrag-third  |     return cls(*args, **kwargs)
lightrag-third  |            ^^^^^^^^^^^^^^^^^^^^
lightrag-third  |   File "/app/lightrag/kg/neo4j_impl.py", line 72, in __init__
lightrag-third  |     f"Using NEO4J_WORKSPACE environment variable: '{neo4j_workspace}' (overriding '{self.workspace}/{self.namespace}')"
lightrag-third  |                                                                                     ^^^^^^^^^^^^^^
lightrag-third  | AttributeError: 'Neo4JStorage' object has no attribute 'workspace'

### Additional Information

- LightRAG Version: v1.4.9.9
- Operating System: docker
- Python Version: used in v1.4.9.9 image

**Comment by danielaskdd** [comment]
PR #2526 resolved this Issue.  v1.4.9.10  released

**Comment by akash171198** [comment]
@danielaskdd Thanks, it worked in new update
